### ISSUE TITLE
Not linking in Windows

### ISSUE THREAD

**Issue by memsharded** [darcamo/conan-openblas#1]
Hi!

I have tried to build this in windows, and the test-package was failing to link. The reason is that in windows the folder is not called "lib64" but "lib". It worked doing:

```diff
(conanpip) λ git diff
diff --git a/conanfile.py b/conanfile.py
index 0587cdf..96bd286 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -56,7 +56,8 @@ endif(CCACHE_FOUND)''')
         cmake.install()

     def package_info(self):
-        self.cpp_info.libdirs = ["lib64"]
+        if self.settings.os != "Windows":
+            self.cpp_info.libdirs = ["lib64"]
```

**Comment by darcamo** [comment]
I have changed to 
```python
self.cpp_info.libdirs = ["lib64", "lib"]
```
without the if test for windows, since in some Linux distributions the folder might also be called just `lib` even in a 64 bits system, but a lib64 folder would not exist in a 32 bits system.

What I have in mind is that it should try to find the library first in the lib64 folder and if that does not work because the folder does not exist then look in the lib folder.

**Comment by memsharded** [comment]
Actually, the "correct" way would be to have always the "lib" folder irrespective of the architecture. Conan already manages the different binaries, and that folder naming is just a workaround of the original build system. Maybe a ``try: shutil.move("lib64", "lib") except: ...`` in the ``package()`` method would do the work too.

I think this issue can be closed then. Cheers!

**Comment by darcamo** [comment]
This makes sense and It might be the best option.

But what if cmake.install for some other library actually creates the two folders? I'm don't know if that ever happens.

**Comment by memsharded** [comment]
Hi!
Yes, if cmake.install() generates and put libraries, for the same architecture, in 2 different folders, definitely you want to add both to ``self.cpp_info.libdirs``. However, in my experience most of the times when this happens is because the build is actually building 2 architectures at the same time. Conan packages would typically just package 1 architecture (for reusing the build and being efficient, the ``build_id()`` method could be used)
