### ISSUE TITLE
Are you publishing this recipe on bintray?

### ISSUE THREAD

**Issue by danielgindi** [darcamo/conan-openblas#2]
I know it's not an "issue", sorry, but I have to know before I start compiling it locally.
Thank you!

**Comment by darcamo** [comment]
I'm publishing this on bintray for my own usage (and colegues), as well as some other recipes. 
The repository is 
https://bintray.com/darcamo/cppsim/

Basically, any conan-<something> repository on my github account is compiled and uploaded to this bintray repository.

You can add this to your conan, if you want, with the command 
```bash
conan remote add darcamo-bintray https://api.bintray.com/conan/darcamo/cppsim
```
The name "darcamo-bintray" can be anything you want.

I build this with a few docker images to compile with gcc 7 and 8, as well as clang 5 and 6. The generated binaries should work for most linux distributions and I know that they work in ubuntu and arch linux.

**Comment by danielgindi** [comment]
Thanks :-)
